services:
  - type: web
    name: earnedpay-backend
    env: docker
    dockerFilePath: Dockerfile
    envVars:
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
